OnlineShoppingStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.Domain.Entities;
using OnlineShoppingStore.WebUI.Models;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }


        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }



        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }


        //private Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if(cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

OnlineShoppingStore.WebUI/Controllers/NavController.cs
using OnlineShoppingStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

OnlineShoppingStore.WebUI/Controllers/ProductController.cs
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.Domain.Concrete;
using OnlineShoppingStore.Domain.Entities;
using OnlineShoppingStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository repository;
        public int PageSize = 4;
        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }

        // GET: Product
       

        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                            .Where(p=> category== null || p.Category== category)
                            .OrderBy(p => p.ProductId)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                                repository.Products.Count() :
                                repository.Products.Where(p => p.Category == category).Count()
                
                },

                CurrentCategory = category


            };

            return View(model);
        }

       
        [HttpPost]
        public ActionResult List(string searchTerm)
        {
            EFDbContext db = new EFDbContext();
            ProductsListViewModel model = new ProductsListViewModel();
            
            if (String.IsNullOrEmpty(searchTerm))
            {
                model.Products = db.Products;
            }
            else
            {
                model.Products = db.Products.Where(x => x.Name.StartsWith(searchTerm));
            }

            
            model.PagingInfo = new PagingInfo();
            model.PagingInfo.CurrentPage = 1; model.PagingInfo.ItemsPerPage = 1; model.PagingInfo.TotalItems = 1;
            
            model.CurrentCategory = db.Products.Where(p => p.Category == model.CurrentCategory).ToString();
            

            return View(model);
        }

        public JsonResult GetProducts(string term)
        {
            EFDbContext db = new EFDbContext();
            

            List<string> products = db.Products.Where(s => s.Name.StartsWith(term)).Select(x => x.Name).ToList();
            return Json(products, JsonRequestBehavior.AllowGet);

        }
    }
}

OnlineShoppingStore.WebUI/Views/Shared/ProductSummary.cshtml
@model OnlineShoppingStore.Domain.Entities.Product

<div class=" row" style="margin-right:5px; margin-bottom:5px; background-color:white; padding: 6px;">
    <div class="col-md-2 col-lg-2 col-sm-2" style="background-color:black;">
        
            <img src="@Model.ImagePath" class="img-responsive" />
        </div>
    <div class="col-md-10 col-lg-10 col-sm-10" style="margin-top:-13px;">
        <h3>
            <span class="label" style="background-color:#474D70;">
                <strong style="">@Model.Name </strong>
            </span>
            <span class="pull-right label label-danger">@Model.Price.ToString("c")</span>
        </h3>

        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.ProductId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Add to cart" />
            </div>
        }

        <span class="lead">@Model.Description</span>
    </div>
</div>

OnlineShoppingStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @{
            var userName = HttpContext.Current.User.Identity.Name;
            if (userName != "")
            {
                <h3 style="padding-right:22px; padding-left:18px;">
                    @Html.ActionLink("Online Shopping Store", "List", "Product")
                <span class="btn-info btn pull-right">
                    @Html.ActionLink(HttpContext.Current.User.Identity.Name + " - Logout", "Logout", "Account")
                </span>
            </h3>
            }
        }

        @RenderBody()
    </div>
</body>

OnlineShoppingStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Shopping Store</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />

    <script>
    window.addEventListener("load", function () {
        var load_screen = document.getElementById("load_screen");
        document.body.removeChild(load_screen);
    });
    </script>

    
</head>
<body style="background: url(http://www.planwallpaper.com/static/images/824183-green-wallpaper.jpg) no-repeat center center fixed; background-size: cover;">
    <br /> 
    <div id="load_screen">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    </div>
                    <div id="loading" class="col-md-4">
                        <img src="images/loading3.gif" alt="" style="">
                    </div>
                </div>
        </div>
     </div>
    <div class="container">
        <div class="navbar navbar" role="navigation" style="background-color:transparent; margin-bottom: -5px;">
            <a class="navbar-brand" href="#">
                @*<span class="hidden-xs">Online Shopping Store</span>
                    <div class="visible-xs">Online</div>
                    <div class="visible-xs">Shopping</div>
                    <div class="visible-xs">Store</div>*@
                
                <img src="~/images/slogo2.png" id="logo" style="height: 250%; margin-left: 0px; margin-top: -13px;"/>
                
            @Html.Action("Summary", "Cart")
        </div>

</div>

        <div class="container">

            <br />
            <div id="categoris" class="col-lg-2">
                @Html.Action("Menu", "Nav")

            </div>
            <div class="col-lg-10">
                @RenderBody()

            </div>



        </div>


        <!-- section start -->
        <!-- ================ -->
        <footer>

            <!-- ================ -->
            <div class="subfooter">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <br /><br /><br />
                            
                                <p class="text-center"> <span class="label ">Copyright © <a target="_blank" href="http://saideep-chhetri.co.uk/">Saideep Raj Chhetri 2016</a>. </span></p>
                            
</div>
                    </div>
                </div>
            </div>
            <!-- .subfooter end -->

        </footer>
        <!-- footer end -->
        <!--




        <!-- Auto run slides -->
        <script type="text/javascript">
            $('.carousel').carousel({ interval: 4000 })
        </script>﻿


</body>
</html>